version: '2'
services:
  app:
    image: "docker-spring-boot:latest"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socialmedia_app
    depends_on:
      - postgres
    ports:
      - 8080:8080
    links:
      - postgres:socialmedia
  postgres:
    container_name: socialmedia
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=socialmedia
      - POSTGRES_PASSWORD=socialmedia
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#      # copy the sql script to create tables
#      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"